### ISSUE TITLE
Strings not updated correctly

### ISSUE THREAD

**Issue by jaumebd** [crowdin/mobile-sdk-android#142]
For some reason I can't see and use the updated strings.

I'm forcing the update from Crowdin using the following command:

I have the following configuration in my application:
```
Crowdin.init(
            context = applicationContext,
            config = CrowdinConfig.Builder()
                .withDistributionHash("aaa")
                .build()
        )
```

And I force the update of Crowdin string to get the new ones:

```
val bundleString = getString(R.string.abc)

Crowdin.forceUpdate(this) {
    val updatedString = getString(R.string.abc)
}
```

The value of bundleString is the one that I have in my strings.xml file.

When doing the force update, I see that Crowdin update is working as expected and the DataManager.updateData enters in the onDataLoaded callback. On this callback I can see the string "abc" with a different value than the one I have in my app bundle. 

I understand that after this forceUpdate if I get the resource I should see the updated value from Crowdin, but this is not the case, bundleString and updatedString both have the same value.

Is there something that I'm missing, or I have misunderstood?

Thanks

**Comment by ira-sem** [comment]
Hi @jaumebd ! Have you released the distribution?

**Comment by jaumebd** [comment]
Hi @ira-sem!

Yes, I released the distribution.

In fact when I execute the Crowdin.forceUpdate() I see the string translated in the response.

**Comment by BozhenaDobrovolska** [comment]
Hi @jaumebd!

Thank you for the reply!

Could you please also have a look at [this](https://github.com/crowdin/mobile-sdk-android#notes) (8th statement) and let me know whether this is what you expected from the Crowdin.forceUpdate(this) method?

Meanwhile, I will check everything with our devs as well

**Comment by jaumebd** [comment]
Hi @BozhenaDobrovolska!

I haven't implemented the shake detector (8th statement). I'm just calling the Crowdin.forceUpdate(this) method manually

**Comment by MykhailoNester** [comment]
Hi @jaumebd, tested `forceUpdate` functionality locally in `crowdin-example` project and it works fine for me.

 As you can see on screenshot after `forceUpdate` method executed we can get new resource. Log message displays before/after values.
 
<img width="611" alt="Screenshot 2021-08-05 at 20 15 42" src="https://user-images.githubusercontent.com/9447674/128394036-b37f9c65-27b7-41b9-9ffd-a8dace555722.png">

Please check example project to see how SDK is integrated.

How to check usage of `forceUpdate` method in example project:
Precondition: set device language to `English`

- Set distribution hash in `App.kt` file. Disable other optional feature like realtime preview and screenshots;
- Navigate to `SettingsFragment.kt` -> `onSpinnerItemSelected` to check `forceUpdate` usage.
- Launch app -> navigate to `Settings` switch language to `de-DE` it will trigger `forceUpdate`. 

For this test case you can use distribution_hash: `84dbaa85c81c6500b65c94876j9` 


I guess that you don't have this part in your activity, and that's why it is the same resource:

```
override fun getDelegate() = BaseContextWrappingDelegate(super.getDelegate())
```

**Comment by jaumebd** [comment]
In fact I forgot to add:

override fun getDelegate() = BaseContextWrappingDelegate(super.getDelegate())

Thanks!
