### ISSUE TITLE
User's privacy

### ISSUE THREAD

**Issue by M66B** [crowdin/mobile-sdk-android#28]
This is certainly an interesting addition to Crowdin, but how about the privacy of the app users?

Should there be a privacy policy? What should the policy contain? How can users opt-in (not opt-out!).

IMHO this should be documented on the main page, also to take away any concerns developers may have.

**Comment by dies** [comment]
yeap. improving the docs, thank you for sharing!

SDK has three features
 1. automatic screenshots from the app to Crowdin
 2. live preview of translations 
 3. CDN. translations delivery to the end-users

#1 and #2 are supposed to be used in the "staging" or "debug" mode. Meaning, if you decide to use those two features, they never affect the code you deliver to your end-users

#3 requires an app's production code change, we believe it won't affect end-user privacy because
 - the SDK code is opensource, it's clear what the code does
 - the code only downloads latest translations from trusted, highly reliable source

**Comment by M66B** [comment]
More and more people are critical about their online privacy, so IMHO saying "*only downloads latest translations from trusted, highly reliable source*" is insufficient and might even violate EU privacy laws. People complain about less these days, see for example [this Bugsnag issue](https://github.com/bugsnag/bugsnag-android/issues/533).

**Comment by dies** [comment]
> saying "is opensource" and "only downloads latest translations from trusted, highly reliable source" is insufficient

thank you very much for the input! we appreciate that a lot!

we are reviewing all of the documentation and will articulate to our users what privacy matters should be considered when integrating Crowdin Android/iOS SDK CDN feature

**Comment by M66B** [comment]
To add some more background, Ubuntu used Amazon services in the past too, which was critically received to say the least. Read for example this article:

https://www.gnu.org/philosophy/ubuntu-spyware.html

Note that this was 2016, so it would not be very smart to make the same mistake 4 years later. Just saying.

**Comment by andrii-bodnar** [comment]
Hello, @M66B !
We've updated Readme and added the "Security" [section](https://github.com/crowdin/mobile-sdk-android#security) to clarify all the privacy policy questions.

**Comment by M66B** [comment]
That's a big improvement. It would help to document in a few words how to opt-in (never opt-out!).
